/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RndLogin.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    height: 405,
    id: 'basePanel',
    width: 627,
    activeItem: 0,
    layout: {
        type: 'card'
    },
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    id: 'loginPanel',
                    title: 'LoginPanel',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Login'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Password'
                        },
                        {
                            xtype: 'button',
                            text: 'Login',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'homePanel',
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'cycle',
                                    showText: true,
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'MenuOne',
                                                checked: true,
                                                listeners: {
                                                    click: {
                                                        fn: me.onMenucheckitemClick,
                                                        scope: me
                                                    }
                                                }
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item',
                                                checked: false
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item',
                                                checked: false
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    showText: true,
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'MenuTwo',
                                                checked: true,
                                                listeners: {
                                                    click: {
                                                        fn: me.onMenucheckitemClick1,
                                                        scope: me
                                                    }
                                                }
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item',
                                                checked: false
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item',
                                                checked: false
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    showText: true,
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'MenuThree',
                                                listeners: {
                                                    click: {
                                                        fn: me.onMenucheckitemClick2,
                                                        scope: me
                                                    }
                                                }
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    showText: true,
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'MenuWizard',
                                                listeners: {
                                                    click: {
                                                        fn: me.onMenucheckitemClick3,
                                                        scope: me
                                                    }
                                                }
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    showText: true,
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'xyz signed in.'
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Sign Out'
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'panel',
                            id: 'homeBody',
                            activeItem: 0,
                            layout: {
                                type: 'card'
                            },
                            title: '',
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Menu One Panel'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Menu Two Panel'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Menu Three Panel'
                                },
                                {
                                    xtype: 'panel',
                                    id: 'wizardBasePanel',
                                    activeItem: 0,
                                    layout: {
                                        type: 'card'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            id: 'stepone',
                                            title: '',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Welcome to Wizard UI ......Step One of the Wizard Flow'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Next',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick1,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            id: 'steptwo',
                                            title: '',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Step Two Of wizard flow'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Next',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick2,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            id: 'stepthree',
                                            title: '',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Step Three of Wizard Flow'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Finish',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick3,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            id: 'endWizard',
                                            title: '',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Congrats you completed the wizard..now use menus to change screen please :)'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {

        Ext.getCmp('basePanel').getLayout().setActiveItem(1);
    },

    onMenucheckitemClick: function(item, e, options) {
        Ext.getCmp('homeBody').getLayout().setActiveItem(0);
    },

    onMenucheckitemClick1: function(item, e, options) {
        Ext.getCmp('homeBody').getLayout().setActiveItem(1);
    },

    onMenucheckitemClick2: function(item, e, options) {
        Ext.getCmp('homeBody').getLayout().setActiveItem(2);
    },

    onMenucheckitemClick3: function(item, e, options) {
        Ext.getCmp('homeBody').getLayout().setActiveItem(3);
        Ext.getCmp('wizardBasePanel').getLayout().setActiveItem(0);
    },

    onButtonClick1: function(button, e, options) {
        Ext.getCmp('wizardBasePanel').getLayout().setActiveItem(1);
    },

    onButtonClick2: function(button, e, options) {
        Ext.getCmp('wizardBasePanel').getLayout().setActiveItem(2);
    },

    onButtonClick3: function(button, e, options) {
        Ext.getCmp('wizardBasePanel').getLayout().setActiveItem(3);
    }

});