/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoEbpp.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    height: 600,
    width: 850,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'image',
                            height: 32,
                            width: 431,
                            src: 'images/stg1.png'
                        },
                        {
                            xtype: 'label',
                            text: ' Last Login Time: 1/1/13 3:23'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/cogwheel.png',
                            text: ''
                        },
                        {
                            xtype: 'cycle',
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Hi, Donald Smith',
                                        checked: true
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/bell.png',
                            text: ''
                        },
                        {
                            xtype: 'button',
                            icon: 'images/question.png',
                            text: ''
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'cycle',
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Home',
                                        checked: true
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'cycle',
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'My Billings',
                                        checked: true
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'cycle',
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'My Policies',
                                        checked: true
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'cycle',
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'My Claims'
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'cycle',
                            showText: true,
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'My Resource Centre',
                                        checked: true
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    },
                                    {
                                        xtype: 'menucheckitem',
                                        text: 'Menu Item',
                                        checked: false
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'hiddenfield',
                            width: 20,
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'textfield',
                            padding: 0,
                            fieldLabel: 'Search',
                            labelPad: 0,
                            labelWidth: 50,
                            blankText: '',
                            emptyText: 'Type your search here'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    height: 510,
                    layout: {
                        type: 'column'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'panel',
                            title: '',
                            columnWidth: 0.7,
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 150,
                                    bodyCls: '',
                                    title: 'My Account Summary',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            bodyCls: '',
                                            title: '',
                                            scroll: 'none',
                                            store: 'MyJsonStore',
                                            viewConfig: {

                                            },
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'type',
                                                    text: 'Type'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'insured',
                                                    text: 'Insured'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'period',
                                                    text: 'Period'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'premium',
                                                    text: 'Premium'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'status',
                                                    text: 'Status'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: 150,
                                    width: 635,
                                    bodyCls: '',
                                    title: 'Direct Billed Policy Summary',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            height: 91,
                                            title: '',
                                            scroll: 'none',
                                            store: 'MyJsonStore1',
                                            viewConfig: {

                                            },
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'type',
                                                    text: 'Type'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'insured',
                                                    text: 'Insured'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'period',
                                                    text: 'Period'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'premium',
                                                    text: 'Premium'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'status',
                                                    text: 'Status'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    layout: {
                                        type: 'column'
                                    },
                                    bodyCls: 'PanelBackground',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'tabpanel',
                                            width: 243,
                                            title: 'My Coverages',
                                            activeTab: 0,
                                            columnWidth: 0.4,
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    height: 200,
                                                    width: 602,
                                                    layout: {
                                                        columns: 2,
                                                        type: 'table'
                                                    },
                                                    bodyCls: 'PanelBackground',
                                                    bodyPadding: 5,
                                                    title: 'Auto',
                                                    items: [
                                                        {
                                                            xtype: 'hiddenfield',
                                                            height: 20,
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'hiddenfield',
                                                            height: 20,
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Towing'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Personal Injury'
                                                        },
                                                        {
                                                            xtype: 'hiddenfield',
                                                            height: 20,
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'hiddenfield',
                                                            height: 20,
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Car Repair'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Accident Forgiveness'
                                                        },
                                                        {
                                                            xtype: 'hiddenfield',
                                                            height: 20,
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'hiddenfield',
                                                            height: 20,
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Multi  Discount'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Unlimited Rental'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    bodyCls: 'PanelBackground',
                                                    title: 'Home'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            width: 223,
                                            layout: {
                                                type: 'column'
                                            },
                                            title: '',
                                            columnWidth: 0.6,
                                            items: [
                                                {
                                                    xtype: 'image',
                                                    height: 200,
                                                    width: 77,
                                                    maintainFlex: false,
                                                    src: 'images/image_ad1.png',
                                                    columnWidth: 0.5
                                                },
                                                {
                                                    xtype: 'panel',
                                                    baseCls: 'PanelBackground',
                                                    bodyPadding: 10,
                                                    title: '',
                                                    columnWidth: 0.5,
                                                    items: [
                                                        {
                                                            xtype: 'hiddenfield',
                                                            height: 30,
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Multi-Policy Discount'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Good Student Discount'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Exclusive Group Savings'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            fieldLabel: '',
                                                            boxLabel: 'Multi Car Discount'
                                                        },
                                                        {
                                                            xtype: 'hiddenfield',
                                                            height: 30,
                                                            fieldLabel: 'Label'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Get a Online Quote'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 510,
                            title: '',
                            columnWidth: 0.3,
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    height: 106,
                                    activeTab: 2,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 79,
                                            bodyCls: 'PanelBackground',
                                            bodyPadding: 10,
                                            title: 'AutoClaims',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    icon: 'images/bell.png',
                                                    iconAlign: 'top',
                                                    iconCls: 'PanelBackground',
                                                    text: 'Intimated'
                                                },
                                                {
                                                    xtype: 'button',
                                                    icon: 'images/bell.png',
                                                    iconAlign: 'top',
                                                    iconCls: 'PanelBackground',
                                                    text: 'Pending'
                                                },
                                                {
                                                    xtype: 'button',
                                                    icon: 'images/bell.png',
                                                    iconAlign: 'top',
                                                    iconCls: 'PanelBackground',
                                                    text: 'Settled'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            bodyCls: 'PanelBackground',
                                            title: 'Home Claims'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: 117,
                                    width: 441,
                                    bodyCls: 'PanelBackground',
                                    bodyPadding: 5,
                                    title: 'Find Auto Repair Centre',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Enter a zip code',
                                            size: 16
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Find within...',
                                            size: 16
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/icon3.png',
                                            iconCls: '',
                                            text: 'Go'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: 95,
                                    html: '<table>\n<tr><td><img src=\'images/bell.png\' /></td><td>Agent Details</td>\n</tr>\n<tr>\n<td></td><td>Larsen Insurance Solutions <img src=\'images/bell.png\' /><br><img src=\'images/bell.png\' />972-373-8392 &nbsp;<img src=\'images/bell.png\' />id@gmail.com</td>\n</tr>\n</table>',
                                    tpl: [
                                        'some html goes here<br>',
                                        'ha ha'
                                    ],
                                    bodyCls: 'PanelBackground',
                                    title: 'Agent Details'
                                },
                                {
                                    xtype: 'panel',
                                    height: 93,
                                    html: '<table>\n<tr><td><img src=\'images/bell.png\' /></td><td>Customer Support</td>\n</tr>\n<tr>\n<td></td><td>Enjoy peace of mind. <br> Have a question? Ask our people.</td>\n</tr>\n</table>',
                                    bodyCls: 'PanelBackground',
                                    title: 'Customer Support'
                                },
                                {
                                    xtype: 'panel',
                                    html: '<img src=\'images/icon3.png\' />Report lost of stolen card<br>\n<img src=\'images/icon3.png\' />Insurance Coverage Calcukator<br>\n<img src=\'images/icon3.png\' />Enroll for eBill Statement',
                                    bodyCls: 'PanelBackground',
                                    title: 'Repair Centre'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 60,
                    bodyCls: 'PanelBackground',
                    title: '',
                    items: [
                        {
                            xtype: 'label',
                            html: 'Copyright @ 2009 MajescoMastek - All rights reserved worldwide.  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href=\'#\'>Privacy</a> | <a href=\'#\'>Legacy</a> | <a href=\'#\'>Security</a> | <a href=\'#\'>Sitemap</a>',
                            text: ''
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});