/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    height: 600,
    width: 800,
    title: 'Customer Information',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 268,
                    title: 'Customer Listing',
                    store: 'MyJsonStore',
                    viewConfig: {

                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'firstName',
                            text: 'FirstName'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lastName',
                            text: 'LastName'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'address',
                            text: 'Address'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'email',
                            text: 'Email'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'voice',
                            text: 'Voice'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'custdet',
                    title: 'New Customer Details',
                    items: [
                        {
                            xtype: 'form',
                            id: 'myform',
                            bodyPadding: 10,
                            title: 'New Customer',
                            url: 'post1.php',
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'firstName',
                                    fieldLabel: 'First Name',
                                    emptyText: 'Anthony'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'lastName',
                                    fieldLabel: 'Last Name',
                                    emptyText: 'Gonsalves'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'address',
                                    fieldLabel: 'Address',
                                    emptyText: 'Prem Galli'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'email',
                                    fieldLabel: 'Email',
                                    emptyText: 'ant.gon@gmail.com'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'voice',
                                    fieldLabel: 'Voice',
                                    emptyText: 9484838383
                                },
                                {
                                    xtype: 'button',
                                    text: 'Create New',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        if(Ext.getCmp('myform').getForm()){

            Ext.getCmp('myform').getForm().submit();

        }

    }

});