/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoStgTab.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    height: 501,
    width: 750,
    title: 'My Insurance Portal',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 3,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'My  Profile',
                            items: [
                                {
                                    xtype: 'form',
                                    layout: {
                                        type: 'column'
                                    },
                                    bodyPadding: 10,
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Customer Id'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'First Name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Middle Name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Last Name'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            fieldLabel: 'Mailing Addess'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            fieldLabel: 'Permanent Address'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'My Policies',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: 'My Grid Panel',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'String'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Number'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Date'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Boolean'
                                        }
                                    ],
                                    viewConfig: {

                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Details',
                            items: [
                                {
                                    xtype: 'form',
                                    layout: {
                                        type: 'auto'
                                    },
                                    bodyPadding: 10,
                                    title: 'Policy Details',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Policy Number'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Policy Holder'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Policy Date'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Effective Start Date'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Effective End Date'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Policy Type'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    maintainFlex: false,
                                    layout: {
                                        type: 'column'
                                    },
                                    bodyPadding: 10,
                                    title: 'Details for [Policy Type]',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Payments',
                            items: [
                                {
                                    xtype: 'form',
                                    height: 212,
                                    width: 765,
                                    layout: {
                                        columns: 2,
                                        type: 'table'
                                    },
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '  Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label',
                                            colspan: 2
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'splitter'
                                },
                                {
                                    xtype: 'form',
                                    height: 133,
                                    bodyPadding: 10,
                                    title: 'My Form'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'New Offerings'
                        },
                        {
                            xtype: 'panel',
                            title: 'My Notifications'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});