/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyNavigationView', {
    extend: 'Ext.navigation.View',

    config: {
        html: '',
        id: 'navigator',
        layout: {
            animation: false,
            type: 'card'
        },
        items: [
            {
                xtype: 'panel',
                layout: {
                    type: 'vbox'
                },
                title: '',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        id: 'toolbar',
                        title: 'Engage',
                        flex: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'settingsButton',
                                text: 'Settings'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                id: 'refreshButton',
                                icon: 'images/refresh.jpg',
                                iconAlign: 'center',
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'carousel',
                        height: '',
                        itemId: 'mycarousel',
                        ui: 'light',
                        flex: 100,
                        items: [
                            {
                                xtype: 'panel',
                                height: '',
                                id: 'welcomePanel',
                                layout: {
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'image',
                                        height: '',
                                        ui: '',
                                        src: 'images/top1.jpg',
                                        flex: 60
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        flex: 30,
                                        items: [
                                            {
                                                xtype: 'image',
                                                height: 80,
                                                width: 160,
                                                src: 'images/news.jpg'
                                            },
                                            {
                                                xtype: 'image',
                                                height: 82,
                                                width: 160,
                                                src: 'images/calendar.jpg'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        id: 'lbelline',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        flex: 5,
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'News',
                                                width: 160
                                            },
                                            {
                                                xtype: 'label',
                                                html: 'Whats On',
                                                width: 160
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        flex: 30,
                                        items: [
                                            {
                                                xtype: 'image',
                                                height: 80,
                                                width: 160,
                                                src: 'images/collaboration.jpg'
                                            },
                                            {
                                                xtype: 'image',
                                                height: 82,
                                                width: 160,
                                                src: 'images/search.jpg'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        id: 'labelline1',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        flex: 5,
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Popular Tasks',
                                                width: 160
                                            },
                                            {
                                                xtype: 'label',
                                                html: 'Find It',
                                                width: 160
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        flex: 30,
                                        items: [
                                            {
                                                xtype: 'image',
                                                height: 80,
                                                width: 160,
                                                src: 'images/checklist.jpg'
                                            },
                                            {
                                                xtype: 'image',
                                                height: 82,
                                                width: 160,
                                                src: 'images/creditcard.jpg'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        id: 'labelline1',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        flex: 5,
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Report It',
                                                width: 160
                                            },
                                            {
                                                xtype: 'label',
                                                html: 'Payments',
                                                width: 160
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'newsPanel',
                                items: [
                                    {
                                        xtype: 'list',
                                        height: 480,
                                        width: '',
                                        itemTpl: [
                                            '<table>',
                                            '<tr>',
                                            '<td>',
                                            '<image src=\'images/compass.jpg\' />  ',
                                            '</td>',
                                            '<td>',
                                            '<font size=\'3\' color=\'red\'>{textdesc}</font><br>',
                                            '<font size=\'2\' color=\'blue\'>{textdet}</font>',
                                            '<br>',
                                            '</td>',
                                            '</tr>',
                                            '<table>'
                                        ],
                                        store: 'MyJsonStore'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'taskPanel',
                                items: [
                                    {
                                        xtype: 'list',
                                        height: 480,
                                        width: '',
                                        itemTpl: [
                                            '<table>',
                                            '<tr>',
                                            '<td>',
                                            '<image src=\'images/compass.jpg\' />  ',
                                            '</td>',
                                            '<td>',
                                            '<font size=\'3\' color=\'red\'>{textdesc}</font><br>',
                                            '<font size=\'2\' color=\'blue\'>{textdet}</font>',
                                            '<br>',
                                            '</td>',
                                            '</tr>',
                                            '<table>'
                                        ],
                                        store: 'MyJsonStore'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'findPanel',
                                items: [
                                    {
                                        xtype: 'list',
                                        height: 480,
                                        width: '',
                                        itemTpl: [
                                            '<table>',
                                            '<tr>',
                                            '<td>',
                                            '<image src=\'images/compass.jpg\' />  ',
                                            '</td>',
                                            '<td>',
                                            '<font size=\'3\' color=\'red\'>{textdesc}</font><br>',
                                            '<font size=\'2\' color=\'blue\'>{textdet}</font>',
                                            '<br>',
                                            '</td>',
                                            '</tr>',
                                            '<table>'
                                        ],
                                        store: 'MyJsonStore'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'contentPanel',
                                items: [
                                    {
                                        xtype: 'list',
                                        height: 480,
                                        width: '',
                                        itemTpl: [
                                            '<table>',
                                            '<tr>',
                                            '<td>',
                                            '<image src=\'images/compass.jpg\' />  ',
                                            '</td>',
                                            '<td>',
                                            '<font size=\'3\' color=\'red\'>{textdesc}</font><br>',
                                            '<font size=\'2\' color=\'blue\'>{textdet}</font>',
                                            '<br>',
                                            '</td>',
                                            '</tr>',
                                            '<table>'
                                        ],
                                        store: 'MyJsonStore'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'reportPanel',
                                items: [
                                    {
                                        xtype: 'list',
                                        height: 480,
                                        width: '',
                                        itemTpl: [
                                            '<table>',
                                            '<tr>',
                                            '<td>',
                                            '<image src=\'images/compass.jpg\' />  ',
                                            '</td>',
                                            '<td>',
                                            '<font size=\'3\' color=\'red\'>{textdesc}</font><br>',
                                            '<font size=\'2\' color=\'blue\'>{textdet}</font>',
                                            '<br>',
                                            '</td>',
                                            '</tr>',
                                            '<table>'
                                        ],
                                        store: 'MyJsonStore'
                                    }
                                ]
                            },
                            {
                                xtype: 'navigationview',
                                id: 'paymentsnav',
                                items: [
                                    {
                                        xtype: 'panel',
                                        id: 'paymentsPanel',
                                        items: [
                                            {
                                                xtype: 'list',
                                                height: 480,
                                                id: 'paymentsList',
                                                itemId: 'mylist5',
                                                width: '',
                                                itemTpl: [
                                                    '<table>',
                                                    '<tr>',
                                                    '<td>',
                                                    '<image src=\'images/compass.jpg\' />  ',
                                                    '</td>',
                                                    '<td>',
                                                    '<font size=\'3\' color=\'red\'>{textdesc}</font><br>',
                                                    '<font size=\'2\' color=\'blue\'>{textdet}</font>',
                                                    '<br>',
                                                    '</td>',
                                                    '</tr>',
                                                    '<table>'
                                                ],
                                                store: 'MyJsonStore'
                                            }
                                        ]
                                    }
                                ],
                                navigationBar: {
                                    hidden: true
                                }
                            }
                        ]
                    }
                ]
            }
        ],
        navigationBar: {
            hidden: true,
            id: 'navbar'
        },
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#settingsButton'
            },
            {
                fn: 'onMycarouselActiveItemChange',
                event: 'activeitemchange',
                delegate: '#mycarousel'
            },
            {
                fn: 'onPaymentsListItemTap',
                event: 'itemtap',
                delegate: '#paymentsList'
            }
        ]
    },

    onMybuttonTap: function(button, e, options) {
        this.push(Ext.create('MyApp.view.SettingsPanel'));

    },

    onMycarouselActiveItemChange: function(container, value, oldValue, options) {

        if(value.id == 'welcomePanel')
        Ext.getCmp('toolbar').setTitle('Welcome');

        if(value.id == 'newsPanel')
        Ext.getCmp('toolbar').setTitle('News');

        if(value.id == 'taskPanel')
        Ext.getCmp('toolbar').setTitle('Tasks');

        if(value.id == 'findPanel')
        Ext.getCmp('toolbar').setTitle('Find');

        if(value.id == 'contentPanel')
        Ext.getCmp('toolbar').setTitle('Contents');

        if(value.id == 'reportPanel')
        Ext.getCmp('toolbar').setTitle('Reports');

        if(value.id == 'paymentsnav')
        Ext.getCmp('toolbar').setTitle('Payments');

    },

    onPaymentsListItemTap: function(dataview, index, target, record, e, options) {
        Ext.getCmp('paymentsnav').push(Ext.create('MyApp.view.PaymentsDetailsPanel'));
    }

});