/*
 * File: app/view/PaymentsDetailsPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PaymentsDetailsPanel', {
    extend: 'Ext.Panel',

    config: {
        items: [
            {
                xtype: 'label',
                html: 'Payment Details'
            },
            {
                xtype: 'textfield',
                label: 'Card Type'
            },
            {
                xtype: 'textfield',
                label: 'Card No'
            },
            {
                xtype: 'datepickerfield',
                label: 'Expiry Date',
                labelAlign: 'top',
                placeHolder: 'mm/dd/yyyy'
            },
            {
                xtype: 'button',
                itemId: 'mybutton8',
                text: 'Submit Payment'
            },
            {
                xtype: 'label',
                html: 'This may take a few minutes please wait for confirmation message'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton8Tap',
                event: 'tap',
                delegate: '#mybutton8'
            }
        ]
    },

    onMybutton8Tap: function(button, e, options) {
        Ext.getCmp('paymentsnav').pop();
    }

});