/*
 * File: app/view/SettingsPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SettingsPanel', {
    extend: 'Ext.Panel',

    config: {
        html: '',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton2',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'numberfield',
                label: 'Customer Id',
                labelAlign: 'top'
            },
            {
                xtype: 'passwordfield',
                label: 'Password',
                labelAlign: 'top'
            },
            {
                xtype: 'radiofield',
                label: 'Contact Me',
                labelAlign: 'top'
            },
            {
                xtype: 'sliderfield',
                label: 'Lactose Tolerance',
                labelAlign: 'top'
            },
            {
                xtype: 'selectfield',
                label: 'Audio Visual',
                labelAlign: 'top'
            },
            {
                xtype: 'button',
                itemId: 'mybutton3',
                text: 'Save'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton2Tap',
                event: 'tap',
                delegate: '#mybutton2'
            },
            {
                fn: 'onMybutton3Tap',
                event: 'tap',
                delegate: '#mybutton3'
            }
        ]
    },

    onMybutton2Tap: function(button, e, options) {
        Ext.getCmp('navigator').pop();
    },

    onMybutton3Tap: function(button, e, options) {
        Ext.getCmp('navigator').pop();
    }

});